#file: noinspection HttpUrlsUsage

spring:
  #enable .env.properties file
  config:
    import: optional:classpath:.env.properties

#logging:
#  level:
#    org.apache.kafka: DEBUG

--- # Eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka

--- # Keycloak
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER_HOST:localhost}:8080/realms/DevVault-v2.0

--- # Swagger
springdoc:
  swagger-ui:
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}

--- # Kafka
spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER_HOST_AND_PORT:localhost:9092}

      #configure serialize classes for key & value pair
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.type.mapping: ProjectEvent:com.seyed.ali.projectservice.model.payload.ProjectDTO

    #custom
    topic:
      name: project_name